variables:
  # https://setuptools-git-versioning.readthedocs.io/en/stable/ci.html
  GIT_DEPTH: 0
  VERSION_REGEX: /^v\d+\.\d+\.\d+.*$/

stages:
  - build
  - deploy

release-pypi:
  # 以开发镜像作为执行环境
  image: registry.fiblab.net/general/dev:latest
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ $VERSION_REGEX
  script:
    - poetry git-version
    - poetry config repositories.gitlab "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
    - poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
    - poetry publish -r gitlab --build --no-interaction -v
