"""
ATTENTION: static traffic assignment has more constraints than just running simulation.
If you want to make all driving trips to be assigned to the routes generated by the STA, you need to make sure that the following conditions are met:
1. All trips' departure_time should be set.
2. There must be lane connections between any in_road and out_road within any junctions.

You should also check the statistics returned by the `sta.run` method to see if there are any invalid/ignored trips.
"""

from mosstool.trip.gmns import STA
from mosstool.type import Map, Persons

m = Map() # load your map
persons = Persons() # load your persons

sta = STA(m, "data/temp/sta")

ps, stat = sta.run(persons, reset_routes=True)
print(f"STA finished, {stat}")

# Save the result
with open("data/temp/sta/sta_persons.pb", "wb") as f:
    f.write(ps.SerializeToString())
